import Link from "next/link";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <header className="bg-slate-500 w-screen nav-container">
            <nav className="sign-in-container flex justify-end">
              <SignedOut>
                <SignInButton />
                <SignUpButton></SignUpButton>
              </SignedOut>
              <SignedIn>
                <Link href="/profile">Your Profile</Link>
                <Link href="/">Feed</Link>
                <UserButton />
              </SignedIn>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
